import Phaser from 'phaser';
import mozartImg from '../assets/mozart.png';

export default class BootScene extends Phaser.Scene {
    constructor() {
        super('BootScene');
    }

    preload() {
        // Load the pixel art using the inline data URI generated by Vite
        this.load.image('mozart', mozartImg);
    }

    create() {
        // Just launch MenuScene
        this.scene.start('MenuScene');
    }
}
